FROM python:3.13-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

COPY requirements_test.txt .
RUN pip install -r requirements_test.txt

CMD ["pytest", "tests/", "--cov=custom_components.vav_balancer"]